# Generated by Django 5.0.4 on 2024-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='made_in',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
