# Generated by Django 5.0.4 on 2024-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_products_made_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='category/products/'),
        ),
        migrations.CreateModel(
            name='Vagetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='category/vagetables/')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('made_in', models.CharField(max_length=50)),
                ('price_type', models.CharField(choices=[('USD', '$'), ('UZS', 'sum')], default='UZS', max_length=10, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
