# Generated by Django 5.0.4 on 2024-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_products_image_vagetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='category/product/'),
        ),
    ]
