# Generated by Django 5.0.4 on 2024-04-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_rename_cart_carts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
